-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.my_contacts
(
    contact_id bigserial,
    last_name character varying(30),
    first_name character varying(30),
    phone numeric,
    "e-mail" character varying,
    gender character varying(10),
    birthday date,
    prof_id integer,
    zip_code integer,
    status_id integer,
    PRIMARY KEY (contact_id)
);

CREATE TABLE public.interests
(
    interest_id bigserial,
    interests character varying(30),
    PRIMARY KEY (interest_id)
);

CREATE TABLE public.my_contacts_interests
(
    my_contacts_contact_id bigserial,
    interests_interest_id bigserial
);

CREATE TABLE public.seeking
(
    seeking_id bigserial,
    seeking character varying(20),
    PRIMARY KEY (seeking_id)
);

CREATE TABLE public.seeking_my_contacts
(
    seeking_seeking_id bigserial,
    my_contacts_contact_id bigserial
);

CREATE TABLE public.profession
(
    prof_id serial,
    profession character varying(20),
    PRIMARY KEY (prof_id)
);

CREATE TABLE public.zip_code
(
    zip_code_id smallserial,
    province character varying(15),
    city character varying(20),
    suburb character varying,
    zip_code numeric,
    PRIMARY KEY (zip_code_id)
);

CREATE TABLE public.status
(
    status_id smallserial,
    status character varying(10),
    PRIMARY KEY (status_id)
);

ALTER TABLE public.profession
    ADD FOREIGN KEY (prof_id)
    REFERENCES public.my_contacts (prof_id)
    NOT VALID;


ALTER TABLE public.zip_code
    ADD FOREIGN KEY (zip_code_id)
    REFERENCES public.my_contacts (zip_code)
    NOT VALID;


ALTER TABLE public.status
    ADD FOREIGN KEY (status_id)
    REFERENCES public.my_contacts (status_id)
    NOT VALID;


ALTER TABLE public.interests
    ADD FOREIGN KEY (interest_id)
    REFERENCES public.my_contacts_interests (interests_interest_id)
    NOT VALID;


ALTER TABLE public.my_contacts
    ADD FOREIGN KEY (contact_id)
    REFERENCES public.my_contacts_interests (my_contacts_contact_id)
    NOT VALID;


ALTER TABLE public.seeking
    ADD FOREIGN KEY (seeking_id)
    REFERENCES public.seeking_my_contacts (my_contacts_contact_id)
    NOT VALID;


ALTER TABLE public.my_contacts
    ADD FOREIGN KEY (contact_id)
    REFERENCES public.seeking_my_contacts (seeking_seeking_id)
    NOT VALID;

END;