-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.departments
(
    depts_id bigint NOT NULL,
    depts character varying(100),
    city character varying(100),
    PRIMARY KEY (depts_id)
);

CREATE TABLE public.employees
(
    emps_id bigint NOT NULL,
    first_name character varying(100),
    last_name character varying(100),
    salary money NOT NULL,
    depts_id character varying NOT NULL,
    overtime_hours numeric NOT NULL,
    job_title character varying NOT NULL,
    PRIMARY KEY (emps_id)
);

CREATE TABLE public.overtime
(
    employee character varying(50),
    overtime numeric NOT NULL,
    salary numeric,
    PRIMARY KEY (overtime)
);

CREATE TABLE public.salaries
(
    supervisor character varying(30),
    salary money NOT NULL,
    benefits money,
    PRIMARY KEY (salary)
);

CREATE TABLE public.teacher
(
    id bigint NOT NULL,
    first_name character varying(25),
    last_name character varying(50),
    school character varying(50),
    hire_date date,
    salary numeric
);

CREATE TABLE public.titles
(
    job_title character varying NOT NULL,
    PRIMARY KEY (job_title)
);

ALTER TABLE public.departments
    ADD FOREIGN KEY (depts_id)
    REFERENCES public.employees (depts_id)
    NOT VALID;


ALTER TABLE public.titles
    ADD FOREIGN KEY (job_title)
    REFERENCES public.employees (job_title)
    NOT VALID;


ALTER TABLE public.salaries
    ADD FOREIGN KEY (salary)
    REFERENCES public.employees (salary)
    NOT VALID;


ALTER TABLE public.overtime
    ADD FOREIGN KEY (overtime)
    REFERENCES public.employees (overtime_hours)
    NOT VALID;

END;